const dotenv = require('dotenv').config('./.env')
const express = require('express')
const dbConnect = require('./config/dbConnect')
dbConnect()
const { errorHandler, notFound } = require('./middlewares/errorHandler')
const app = express()
const cors = require('cors')
const fileuploader = require('express-fileupload')


const authRouter = require('./routes/authRoutes')
const productRouter = require('./routes/productRoute')
const blogRouter = require('./routes/blogRoutes')
const productCategoryRouter = require('./routes/productCategoryRoute')
const blogCategoryRouter = require('./routes/blogCategoryRoutes')
const brandRouter = require('./routes/brandRoutes')
const couponRouter = require('./routes/couponRoute')
const colorRouter = require('./routes/colorRoute')
const enquiryRouter = require('./routes/enquiryRoute')
const uploadRouter = require('./routes/uploadRoute')
const bodyParser = require('body-parser')
const cookieParser = require('cookie-parser')
const morgan = require('morgan')

app.use(morgan('dev'))
app.use(cors())

app.use(fileuploader())
app.use(bodyParser.urlencoded({extended:false}))
app.use(bodyParser.json())
app.use(cookieParser())
app.use('/api/user',authRouter)
app.use('/api/product',productRouter)
app.use('/api/blog',blogRouter)
app.use('/api/productCategory',productCategoryRouter)
app.use('/api/blogCategory',blogCategoryRouter)
app.use('/api/brand',brandRouter)
app.use('/api/coupon',couponRouter)
app.use('/api/color',colorRouter)
app.use('/api/enquiry',enquiryRouter)
app.use('/api/upload',uploadRouter)

app.use(notFound)
app.use(errorHandler)


app.listen(process.env.PORT,()=>{
    console.log(`server running on ${process.env.PORT}`)
})